apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme"
  REDIS_PASSWORD: "changeme"
  S3_ACCESS_KEY: "changeme"
  S3_SECRET_KEY: "changeme"
  GITHUB_TOKEN: "changeme"
  JWT_SECRET: "changeme"
# NOTE: For production, use `kubectl create secret` and do not commit real secrets.