apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
data:
  LOG_LEVEL: "info"
  S3_ENDPOINT: "http://minio:9000"
  S3_BUCKET: "flight-control-artifacts"
  S3_PUBLIC_URL: "http://minio:9000"
  GITHUB_REPO: "your-org/flight-control"
  JWT_ISSUER: "flight-control"